afiliados/urls.py
from . import views
from django.urls import path

urlpatterns = [
   path('afiliadoLista', views.afiliadoLista, name='afiliadoLista'), 
   path('crearAfiliados',views.crearAfiliados, name='crearAfiliados'),
   path('editar_afiliado/<int:afi_id>/', views.editar_afiliado, name='editar_afiliado'),
   path('eliminar_afiliado<int:afi_id>/', views.eliminar_afiliado, name='eliminar_afiliado'),

 
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('afiliados.urls')),
    path('',include('federacion.urls')),
    path('',include('vehiculo.urls')),
    path('',include('tramite.urls')),
    path('',include('usuarios.urls')),
    path('',include('operador.urls')),
    path('',include('log.urls')),
    #path('',include('afiliados.urls')),
]

afiliados/models.py
from django.db import models

from federacion.models import Federacion

class Afiliado(models.Model):
    nombre = models.CharField(max_length=100, blank=False, null=False)
    apellido = models.CharField(max_length=100,blank=False, null=False)
    carnet= models.CharField(max_length=100,blank=False, null=False)
    email = models.EmailField()
    celular = models.CharField(max_length=15, blank=True, null=True)
    direccion = models.CharField(max_length=255, blank=True, null=True)
    fecha_afiliacion = models.DateField(auto_now_add=True)
    federacion=models.ForeignKey(Federacion, on_delete=models.CASCADE)
    flag=models.CharField(max_length=20,
        choices=[('nuevo', 'nuevo'), ('eliminado', 'eliminado'),],
        default='nuevo')
    estado_afiliacion = models.CharField(
        max_length=20,
        choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')],
        default='activo'
    )
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

 

afiliados/forms.py
from django import forms
from .models import Afiliado
class Afiliados(forms.ModelForm):
    class Meta:
        model = Afiliado
        fields= ['nombre','apellido','carnet','email','celular','direccion','federacion']

afiliados/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse

from utils.context_processors import verificarRol
from .forms import Afiliados
from django.urls import reverse
from .models import Afiliado


def afiliadoLista(request):
    resultado = verificarRol(request, ['super_admin','administrador'])
        
    if resultado is not True:
        return resultado
    afiliados = Afiliado.objects.filter(flag='nuevo')
    context={'afiliados':afiliados}


    return render(request, 'afiliados/afiliados.html', context)

def crearAfiliados(request):
    resultado = verificarRol(request, ['super_admin','administrador'])
        
    if resultado is not True:
        return resultado
    if request.method =='POST':
        afiliados=Afiliados(request.POST)
        if afiliados.is_valid():
            afiliados.save()
            return redirect(reverse('afiliadoLista'))
            

    else:
        afiliados=Afiliados()
        context={'afiliados':afiliados}
        return render(request,'afiliados/crear.afiliados.html', context)
    


def editar_afiliado(request, afi_id):
    afili = get_object_or_404(Afiliado, id=afi_id)

    if request.method == 'POST':
        forms = Afiliados(request.POST, instance=afili)
        if forms.is_valid():
            forms.save()
            return redirect('afiliadoLista')
    else:
        forms = Afiliados(instance=afili)

    return render(request, 'afiliados/editar.html', {'forms': forms, 'id': afili.id})

def eliminar_afiliado(request, afi_id):
    afili = get_object_or_404(Afiliado, id=afi_id)
    afili.flag = 'eliminado'
    afili.save()
    return redirect('afiliadoLista')

templates/afiliados/afiliados.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1 class="my-4">Lista de Afiliados</h1>
    <form action="{% url 'afiliadoLista' %}" method="get"></form>
    


    <table class="table table-striped">
        <a href="{% url 'crearAfiliados' %}">registrar</a>
        <thead class="table-dark">
            <tr>
                <th>Número de Afiliado</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Carnet</th>
                <th>Email</th>
                <th>Teléfono</th>
                <th>Dirección</th>
                <th>Federacion</th>
                <th>Fecha de Afiliación</th>
                <th>Estado de Afiliación</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for afiliado in afiliados %}
            <tr>
                <td>{{ afiliado.id}}</td>
                <td>{{ afiliado.nombre }}</td>
                <td>{{ afiliado.apellido }}</td>
                <td>{{ afiliado.carnet }}</td>
                <td>{{ afiliado.email }}</td>
                <td>{{ afiliado.telefono }}</td>
                <td>{{ afiliado.direccion }}</td>
                <td>{{ afiliado.federacion }}</td>
                <td>{{ afiliado.fecha_afiliacion }}</td>
                <td>{{ afiliado.get_estado_afiliacion_display }}</td>
                <td>
                    <a href="" class="btn btn-info btn-sm">Ver</a>
                    <a href="{% url 'editar_afiliado' afiliado.id %}"class="btn btn-warning btn-sm">Editar</a>
                    <a href="{% url 'eliminar_afiliado' afiliado.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="13" class="text-center">No hay afiliados registrados.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/afiliados/crear.afiliados.html
{% extends "base.html" %}
{% block content %}
<form action="{% url 'crearAfiliados' %}" method="POST">
    {% csrf_token %}
    {{afiliados}}
    <Button>guardad</Button>
</form>
{% endblock %}

templates/afiliados/editar.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Editar Afiliado</h2>
    <form action="{% url 'editar_afiliado' id %}" method="POST">
        {% csrf_token %}
        {{ forms.as_p }}
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>
</div>
{% endblock %}